server.port=8083
spring.application.name=frete

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.cache.redis.cache-null-values=false

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.request.exchange.producer=direct.exchange
spring.rabbitmq.request.routing-key.producer=fila.principal
spring.rabbitmq.request.dead-letter.producer=fila.retentativa
spring.rabbitmq.request.parking-lot.producer=fila.erro

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=${MONGODB_URI}